-- CloudMiner HYIP — нове значення transaction_type для бонусу до
-- поповнення (див. наступну міграцію 20260821161000_shop_discount_and_deposit_bonus.sql).
--
-- В ОКРЕМОМУ файлі свідомо: `ALTER TYPE ... ADD VALUE` не можна
-- використати в тій самій транзакції, де нове значення вже
-- використовується (напр. у тілі `create or replace function`, що
-- посилається на нього) — Postgres прямо забороняє це для
-- новододаних enum-лейблів. Розділені файли/виклики гарантують, що
-- `deposit_bonus` вже закомічений як існуюче значення enum ще ДО того,
-- як наступна міграція спробує написати функцію, яка його використовує.
alter type public.transaction_type add value if not exists 'deposit_bonus';
